name: dart_mail
description: This is a command-line utility that takes a single file and can output a number of emails..
version: 1.0.1
repository: https://https://github.com/chris-reynolds/dart_mail

environment:
  sdk: ^3.5.4

dependencies:
  mailer: ^6.2.0
  

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
